name: network_utils
description: "Dart network utils"
version: 0.4.1
homepage: "https://github.com/kit-g/dart-network-utils.git"
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  logging: ^1.2.0
  http: ^1.2.2
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^6.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4
  test: ^1.28.0
